---
AssignmentInConditionalCheck:
CaseMissingElseCheck:
ClassLineCountCheck:
  line_count: 120
ClassNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:
CyclomaticComplexityBlockCheck:
  complexity: 2
CyclomaticComplexityMethodCheck:
  complexity: 2
EmptyRescueBodyCheck:
ForLoopCheck:
MethodLineCountCheck:
  line_count: 5
MethodNameCheck:
  pattern: !ruby/regexp /^[\||\^|\&|\!]$|^[_a-z<>=\[|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/
ModuleLineCountCheck:
  line_count: 120
ModuleNameCheck:
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:
  parameter_count: 4
